server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:dbtest"
    platform: h2
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    #schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      path: /h2 #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      settings:
        web-allow-others: true # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
  jpa:
    show-sql: true #启用SQL语句的日志记录
    generate-ddl: true
    hibernate:
      ddl-auto: update  #设置ddl模式