INSERT INTO USER (ID,NAME,SEX,AGE,CREATE_TIME,MODIFY_TIME) VALUES(
1,'David','0',20,sysdate,sysdate);
INSERT INTO USER (ID,NAME,SEX,AGE,CREATE_TIME,MODIFY_TIME) VALUES(
2,'John','0',22,sysdate,sysdate);
INSERT INTO USER (ID,NAME,SEX,AGE,CREATE_TIME,MODIFY_TIME) VALUES(
3,'Sara','1',24,sysdate,sysdate);